name = "ola2-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "ORDERS_DB"
id = "325414de776f4f17bbaa1f57ffd3ed92"

[vars]
# GEMINI_API_KEY should be set via secrets: wrangler secret put GEMINI_API_KEY
